
import javax.swing.JOptionPane;
import java.io.*;
import java.util.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alejandroxp08
 */
public class InterfazCliente extends javax.swing.JFrame {
    private ArrayList<Pedido> pedidos;
    private Pedido pedidoG;
    private mySingleton ser;
    /**
     * Creates new form InterfazCliente
     */
    public InterfazCliente() throws IOException{
        initComponents();
        pedidos=new ArrayList();
        pedidoG=new Pedido();
        ser=mySingleton.getInstance();
    }

    /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        textfieldObservaciones = new javax.swing.JTextField();
        textfieldDireccion = new javax.swing.JTextField();
        buttonAnadir = new javax.swing.JButton();
        jLabelNombre = new javax.swing.JLabel();
        jLabelCliente = new javax.swing.JLabel();
        jLabelObservaciones = new javax.swing.JLabel();
        textfieldProducName = new javax.swing.JTextField();
        butonAgregar = new javax.swing.JButton();
        textfieldCliente1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textfieldCantidad = new javax.swing.JTextField();
        jLabelCantidad = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("jCheckBoxMenuItem3");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        buttonAnadir.setText("OK");
        buttonAnadir.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    buttonAnadirActionPerformed(evt);
                }
            });

        jLabelNombre.setText("Nombre del Cliente");

        jLabelCliente.setText("Direccion del Cliente");

        jLabelObservaciones.setText("Observaciones");

        butonAgregar.setText("Agregar");
        butonAgregar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    butonAgregarActionPerformed(evt);
                }
            });

        jLabel1.setText("introduzca codigo de producto");

        jLabelCantidad.setText("Cantidad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)
                        .addGap(42, 42, 42)
                        .addComponent(jLabelCantidad))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(textfieldProducName, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(textfieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(butonAgregar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabelNombre))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(textfieldCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabelCliente))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(textfieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabelObservaciones))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(textfieldObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(buttonAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelCantidad)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textfieldProducName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(butonAgregar)
                .addGap(15, 15, 15)
                .addComponent(jLabelNombre)
                .addGap(12, 12, 12)
                .addComponent(textfieldCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabelCliente)
                .addGap(13, 13, 13)
                .addComponent(textfieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabelObservaciones)
                .addGap(6, 6, 6)
                .addComponent(textfieldObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonAnadir)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAnadirActionPerformed
        String nombre =textfieldCliente1.getText();
        pedidoG.setNom(nombre);
        String direccion=textfieldDireccion.getText();
        Direccion direccion1=new Direccion(direccion,0,0);
        pedidoG.setDireccion(direccion1);
        String observaciones=textfieldObservaciones.getText();
        pedidoG.setObs(observaciones);
        Serializacion ser=new Serializacion();
        try{
            ser.abrirsalida2();
            ser.escribir2(pedidoG);
            ser.cerrarsalida2();
        }catch(IOException e){
        }
        JOptionPane.showMessageDialog(null, "El pedido ha sido agregado,"+"el precio Total es: "+pedidoG.precioTotal()+"Bs");
    }//GEN-LAST:event_buttonAnadirActionPerformed

    private void butonAgregarActionPerformed (java.awt.event.ActionEvent evt){//GEN-FIRST:event_butonAgregarActionPerformed
        String codigo=textfieldProducName.getText();
        String cant1=textfieldCantidad.getText();
        int cant=Integer.parseInt(cant1);
        Producto d=new Producto();
        try{
            d=agregarSoli(codigo);
        }catch(IOException e){
        }
        Solicitud s=new Solicitud(d,cant);
        pedidoG.aumen(s);
        pedidos.add(pedidoG);
    }//GEN-LAST:event_butonAgregarActionPerformed

    private Producto agregarSoli(String codigo) throws IOException{
        Producto res=new Producto();
        int cod=Integer.parseInt(codigo);
        try {
            Producto d;
            boolean  bb=true;
            do{
                d =(Producto)ser.getObject().readObject();
                if(d.getCodigo()==cod&&bb){
                    res=d;
                    bb=false;
                }
            } while(d!=null);
        } catch (IOException e) {
        } catch (ClassNotFoundException e) {
        }
        return res;
    }

    /**
     * @param args the command line arguments
     */
    public  void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
                public void run(){
                    try{
                        new InterfazCliente().setVisible(true);
                    }catch(IOException e){
                    }
                }
            });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butonAgregar;
    private javax.swing.JButton buttonAnadir;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelObservaciones;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField textfieldCantidad;
    private javax.swing.JTextField textfieldCliente1;
    private javax.swing.JTextField textfieldDireccion;
    private javax.swing.JTextField textfieldObservaciones;
    private javax.swing.JTextField textfieldProducName;
    // End of variables declaration//GEN-END:variables
}

